services:
  cloudflared:
    build: .
    container_name: cloudflared
    platform: linux/arm64
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token <enter your token here>
    security_opt:
      - no-new-privileges:true   # Prevent privilege escalation
    cap_add:
      - NET_BIND_SERVICE         # Allow binding to privileged ports (e.g., 80, 443)
    cap_drop:
      - ALL                       # Drop all non-essential capabilities
    read_only: true               # Filesystem is read-only for security
    volumes:
      - /tmp                       # Optional: for temporary files (like certificates)

